// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetRockManagment.Data;

#nullable disable

namespace PetRockManagment.Migrations
{
    [DbContext(typeof(PetRockDbContext))]
    partial class PetRockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetRockManagment.Models.PetRock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("bath")
                        .HasColumnType("bit");

                    b.Property<string>("mood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("PetRocks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            bath = true,
                            mood = "happy",
                            name = "ben"
                        },
                        new
                        {
                            id = 2,
                            bath = false,
                            mood = "sad",
                            name = "joe"
                        },
                        new
                        {
                            id = 3,
                            bath = true,
                            mood = "angry",
                            name = "doey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
